name : CI

on:
  push:
    branches: main
  pull_request:
    branches: main

env:
  NB_KERNEL: python3
  MPLBACKEND: Agg

jobs:

  run-tests:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          uv sync --extra dev
          uv run jupyter kernelspec list

      - name: Execute tests
        run: uv run pytest tests/ src/nmaci/
